### PR TITLE
Fix simplified subsumption for ghc-9

### PR DESCRIPTION
**Pull request by locallycompact**
Hi, this allows this repository to build with ghc-9.0 due to the simplified subsumption change.

### CODE REVIEW

**Comment by locallycompact** [comment]
Can this go in? I'd like to be able to build plutus-apps with ghc-9.2

**Review by coot — APPROVED** [review]
LGTM

**Comment by coot** [comment]
Before merging, could you clean the branch frist.  I'd prefer to rebase the single commit on top of current master.

**Comment by coot** [comment]
Fixed via #13.

**Pull request closed without merging**
